#define LIGHT_INFO_SIZE (4 + (4 * 3) + (4 * 3) + 4 + 4)
#define LIGHT_PACKET_SIZE (4 + 4 + 4 + LIGHT_INFO_SIZE)
#define SHADOW_SOURCE_INFO_SIZE ((4 * 4 * 4) + (4 * 4))
#define SHADOW_SOURCE_PACKET_SIZE (4 + SHADOW_SOURCE_INFO_SIZE)
#define MAX_LIGHTS 16
#define LIGHT_DATA_SIZE ((LIGHT_INFO_SIZE * MAX_LIGHTS) + (SHADOW_SOURCE_INFO_SIZE * MAX_LIGHTS * 6))
