#define R32 4
#define RGBA32 (R32 * 4)
#define LIGHT_INFO_SIZE (R32 + (R32 * 3) + (R32 * 3) + R32)
#define LIGHT_PACKET_SIZE (R32 + R32 + R32 + LIGHT_INFO_SIZE + R32)
#define SHADOW_SOURCE_INFO_SIZE ((R32 * 4 * 4) + (R32 * 4))
#define SHADOW_SOURCE_PACKET_SIZE (R32 + SHADOW_SOURCE_INFO_SIZE)
#define MAX_LIGHTS 24
#define LIGHT_DATA_SIZE ((LIGHT_INFO_SIZE * MAX_LIGHTS) + (SHADOW_SOURCE_INFO_SIZE * MAX_LIGHTS * 6))
